cmake_minimum_required(VERSION 3.31)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
project(toolchain-modes-test C CXX ASM)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_library(mode-probe STATIC probe.c probe.cpp probe.asm)
if (REAVEROS_BUILD_MODE STREQUAL "uefi")
    target_compile_definitions(mode-probe PRIVATE EXPECT_WINDOWS_ABI)
endif()
if (REAVEROS_IS_FREESTANDING)
    target_compile_definitions(mode-probe PRIVATE EXPECT_FREESTANDING)
endif()
