cmake_minimum_required(VERSION 3.31)
if (TEST_HEADER_ONLY)
    project(native-header-only LANGUAGES NONE)
    add_custom_target(build-tests)
    return()
endif()
project(native-test-child CXX)
enable_testing()
set(CMAKE_CXX_STANDARD 20)
include("${TEST_REPOSITORY}/cmake/native_tests.cmake")
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_library(fixture-library STATIC support.cpp)
target_compile_definitions(fixture-library PRIVATE "$<$<CONFIG:Release>:EXPECT_RELEASE>")
add_subdirectory(test)
