reaveros_build_environment_base_image=debian:unstable

reaveros_build_environment_packages=(
    automake
    bison
    build-essential
    ccache
    cmake
    cpio
    flex
    git
    libssl-dev
    python3
)
