include_guard(GLOBAL)

function(_reaveros_add_target_maybe_tests _name)
    add_custom_target(${_name})
    if (REAVEROS_ENABLE_UNIT_TESTS)
        add_custom_target(${_name}-build-tests)
    endif()
endfunction()

function(_reaveros_add_aggregate_targets_impl _suffix _use_modes)
    if (NOT "${_suffix}" STREQUAL "")
        _reaveros_add_target_maybe_tests(all-${_suffix})
        set(_suffix "-${_suffix}")
    else()
        add_custom_target(all-build-tests)
    endif()

    foreach (architecture IN LISTS REAVEROS_ARCHITECTURES)
        _reaveros_add_target_maybe_tests(all-${architecture}${_suffix})
    endforeach()

    if (_use_modes)
        set(_modes uefi freestanding hosted)
        if (REAVEROS_ENABLE_UNIT_TESTS)
            list(APPEND _modes tests)
        endif()
        foreach (mode IN LISTS _modes)
            add_custom_target(all-${mode}${_suffix})
            foreach (architecture IN LISTS REAVEROS_ARCHITECTURES)
                add_custom_target(all-${architecture}-${mode}${_suffix})
            endforeach()
        endforeach()
    endif()
endfunction()

function(reaveros_add_aggregate_targets_with_modes _suffix)
    _reaveros_add_aggregate_targets_impl("${_suffix}" TRUE)
endfunction()

function(reaveros_add_aggregate_targets _suffix)
    _reaveros_add_aggregate_targets_impl("${_suffix}" FALSE)
endfunction()

function(_reaveros_register_target_impl _target _head _tail)
    list(LENGTH _tail _tail_length)
    math(EXPR _tail_length_prev "${_tail_length} - 1")
    list(GET _tail ${_tail_length_prev} _last)

    get_target_property(_is_test_target ${_target} _REAVEROS_IS_TEST_TARGET)

    foreach (_index RANGE 0 ${_tail_length_prev})
        list(GET _tail ${_index} _current_element)
        set(_full_list ${_head} ${_current_element})

        if (${_index} EQUAL ${_tail_length_prev} OR NOT "${_last}" STREQUAL "build-tests")
            string(REPLACE ";" "-" _aggregate_target "${_full_list}")
            if (TARGET all-${_aggregate_target})
                set(_is_relevant_aggregate TRUE)
                if (_is_test_target)
                    list(FIND _full_list "tests" _has_tests)
                    list(FIND _full_list "build-tests" _has_build_tests)
                    if (${_has_tests} EQUAL -1 AND ${_has_build_tests} EQUAL -1)
                        set(_is_relevant_aggregate FALSE)
                    endif()
                endif()

                if (_is_relevant_aggregate)
                    add_dependencies(all-${_aggregate_target} ${_target})
                endif()
            endif()
        endif()

        math(EXPR _index_next "${_index} + 1")

        if (${_index_next} LESS ${_tail_length})
            list(SUBLIST _tail ${_index_next} -1 _current_tail)

            _reaveros_register_target_impl(${_target} "${_full_list}" "${_current_tail}")
        endif()
    endforeach()
endfunction()

function(reaveros_register_target _target)
    _reaveros_register_target_impl(${_target} "" "${ARGN}")
endfunction()
