include_guard(GLOBAL)

# Emit quoted CMake arguments rather than forwarding arbitrary command strings
# through CMake lists. This retains semicolons, backslashes, quotes and newlines.
function(_reaveros_quote_test_argument _output _value)
    string(REPLACE "\\" "\\\\" _value "${_value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    string(REPLACE "$" "\\$" _value "${_value}")
    string(REPLACE "\n" "\\n" _value "${_value}")
    string(REPLACE "\r" "\\r" _value "${_value}")
    string(REPLACE "\t" "\\t" _value "${_value}")
    set(${_output} "\"${_value}\"" PARENT_SCOPE)
endfunction()

function(reaveros_import_native_tests)
    cmake_parse_arguments(PARSE_ARGV 0 _import ""
        "COMPONENT;BINARY_DIR;CTEST;CONFIGURATION" "LABELS")
    foreach (_field COMPONENT BINARY_DIR CTEST)
        if (NOT DEFINED _import_${_field} OR "${_import_${_field}}" STREQUAL "")
            message(FATAL_ERROR "Native test discovery requires ${_field}.")
        endif()
    endforeach()
    if (_import_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown native discovery arguments: ${_import_UNPARSED_ARGUMENTS}")
    endif()
    # Header-only/no-test components contribute no registrations. Discovery
    # otherwise follows the existing build-before-CTest workflow.
    if (NOT EXISTS "${_import_BINARY_DIR}/CTestTestfile.cmake")
        return()
    endif()
    set(_configuration "")
    if (NOT "${_import_CONFIGURATION}" STREQUAL "")
        list(APPEND _configuration -C "${_import_CONFIGURATION}")
    endif()
    execute_process(
        COMMAND "${_import_CTEST}" --test-dir "${_import_BINARY_DIR}"
            --show-only=json-v1 ${_configuration}
        RESULT_VARIABLE _result OUTPUT_VARIABLE _json ERROR_VARIABLE _errors
    )
    if (NOT _result STREQUAL "0")
        message(FATAL_ERROR "Could not discover '${_import_COMPONENT}' tests: ${_errors}\n${_json}")
    endif()
    string(JSON _kind ERROR_VARIABLE _error GET "${_json}" kind)
    if (_error OR NOT _kind STREQUAL "ctestInfo")
        message(FATAL_ERROR "Invalid CTest JSON for '${_import_COMPONENT}': ${_error}")
    endif()
    string(JSON _major GET "${_json}" version major)
    if (NOT _major EQUAL 1)
        message(FATAL_ERROR "Unsupported CTest JSON version ${_major} for '${_import_COMPONENT}'.")
    endif()
    string(JSON _count LENGTH "${_json}" tests)
    if (_count EQUAL 0)
        return()
    endif()
    math(EXPR _last "${_count} - 1")
    set(_registrations "")
    foreach (_index RANGE 0 ${_last})
        string(JSON _test GET "${_json}" tests ${_index})
        string(JSON _name GET "${_test}" name)
        set(_parent_name "${_import_COMPONENT} :: ${_name}")
        _reaveros_quote_test_argument(_quoted_name "${_parent_name}")
        string(APPEND _registrations "add_test(${_quoted_name}")
        string(JSON _command_type ERROR_VARIABLE _error TYPE "${_test}" command)
        if (_error)
            # A configuration-dependent empty command remains an empty command;
            # its DISABLED property, if any, is retained below.
            string(APPEND _registrations " \"\"")
        else()
            string(JSON _argc LENGTH "${_test}" command)
            if (_argc EQUAL 0)
                string(APPEND _registrations " \"\"")
            else()
                math(EXPR _argv_last "${_argc} - 1")
                foreach (_argv_index RANGE 0 ${_argv_last})
                    string(JSON _argument GET "${_test}" command ${_argv_index})
                    _reaveros_quote_test_argument(_argument "${_argument}")
                    string(APPEND _registrations " ${_argument}")
                endforeach()
            endif()
        endif()
        string(APPEND _registrations ")\n")

        set(_labels "${_import_LABELS}")
        string(JSON _properties_type ERROR_VARIABLE _error TYPE "${_test}" properties)
        if (NOT _error)
            string(JSON _property_count LENGTH "${_test}" properties)
            if (_property_count GREATER 0)
                math(EXPR _property_last "${_property_count} - 1")
                foreach (_property_index RANGE 0 ${_property_last})
                    string(JSON _property GET "${_test}" properties ${_property_index})
                    string(JSON _property_name GET "${_property}" name)
                    string(JSON _type TYPE "${_property}" value)
                    if (_property_name STREQUAL "RESOURCE_GROUPS")
                        # CTest expands the compact resource grammar into groups
                        # of requirements. Reconstruct that grammar explicitly.
                        set(_value "")
                        string(JSON _groups LENGTH "${_property}" value)
                        if (_groups GREATER 0)
                            math(EXPR _group_last "${_groups} - 1")
                            foreach (_group_index RANGE 0 ${_group_last})
                                if (_group_index GREATER 0)
                                    string(APPEND _value ";")
                                endif()
                                string(APPEND _value "1")
                                string(JSON _requirements LENGTH "${_property}" value ${_group_index} requirements)
                                if (_requirements GREATER 0)
                                    math(EXPR _requirement_last "${_requirements} - 1")
                                    foreach (_requirement_index RANGE 0 ${_requirement_last})
                                        string(JSON _resource GET "${_property}" value ${_group_index}
                                            requirements ${_requirement_index} .type)
                                        string(JSON _slots GET "${_property}" value ${_group_index}
                                            requirements ${_requirement_index} slots)
                                        string(APPEND _value ",${_resource}:${_slots}")
                                    endforeach()
                                endif()
                            endforeach()
                        endif()
                    elseif (_property_name STREQUAL "TIMEOUT_AFTER_MATCH")
                        string(JSON _value GET "${_property}" value timeout)
                        string(JSON _regex_count LENGTH "${_property}" value regex)
                        if (_regex_count GREATER 0)
                            math(EXPR _regex_last "${_regex_count} - 1")
                            foreach (_regex_index RANGE 0 ${_regex_last})
                                string(JSON _regex GET "${_property}" value regex ${_regex_index})
                                string(REPLACE ";" "\\;" _regex "${_regex}")
                                string(APPEND _value ";${_regex}")
                            endforeach()
                        endif()
                    elseif (_type STREQUAL "ARRAY")
                        set(_value "")
                        string(JSON _length LENGTH "${_property}" value)
                        if (_length GREATER 0)
                            math(EXPR _value_last "${_length} - 1")
                            foreach (_value_index RANGE 0 ${_value_last})
                                string(JSON _entry_type TYPE "${_property}" value ${_value_index})
                                if (NOT _entry_type STREQUAL "STRING")
                                    message(FATAL_ERROR
                                        "Unsupported ${_entry_type} entry for '${_parent_name}' property '${_property_name}'.")
                                endif()
                                string(JSON _entry GET "${_property}" value ${_value_index})
                                if (_property_name STREQUAL "DEPENDS"
                                        OR _property_name MATCHES "^FIXTURES_(SETUP|REQUIRED|CLEANUP)$")
                                    set(_entry "${_import_COMPONENT} :: ${_entry}")
                                endif()
                                string(REPLACE ";" "\\;" _entry "${_entry}")
                                if (_value_index GREATER 0)
                                    string(APPEND _value ";")
                                endif()
                                string(APPEND _value "${_entry}")
                            endforeach()
                        endif()
                    elseif (_type STREQUAL "STRING" OR _type STREQUAL "NUMBER" OR _type STREQUAL "BOOLEAN")
                        string(JSON _value GET "${_property}" value)
                    else()
                        message(FATAL_ERROR "Unsupported ${_type} value for '${_parent_name}' property '${_property_name}'.")
                    endif()
                    if (_property_name STREQUAL "LABELS")
                        if (NOT _labels STREQUAL "" AND NOT _value STREQUAL "")
                            string(APPEND _labels ";")
                        endif()
                        string(APPEND _labels "${_value}")
                    else()
                        _reaveros_quote_test_argument(_quoted_property "${_property_name}")
                        _reaveros_quote_test_argument(_quoted_value "${_value}")
                        string(APPEND _registrations
                            "set_tests_properties(${_quoted_name} PROPERTIES ${_quoted_property} ${_quoted_value})\n")
                    endif()
                endforeach()
            endif()
        endif()
        list(REMOVE_DUPLICATES _labels)
        _reaveros_quote_test_argument(_quoted_labels "${_labels}")
        string(APPEND _registrations
            "set_tests_properties(${_quoted_name} PROPERTIES LABELS ${_quoted_labels})\n")
    endforeach()
    # Only fixed registration/property commands are evaluated. Every JSON value
    # is quoted above; metadata is never interpolated as executable CMake code.
    cmake_language(EVAL CODE "${_registrations}")
endfunction()
