include_guard(GLOBAL)

# ExternalProject serializes command arguments as CMake lists. Encode embedded
# separators before that boundary, choosing a marker absent from all arguments
# and the project's source/build paths. Literal pipes stay literal.
function(_reaveros_ep_arguments _output _separator_output _context)
    set(_separator "__reaveros_list_separator__")
    math(EXPR _last "${ARGC} - 1")
    while (TRUE)
        string(FIND "${_context}" "${_separator}" _found)
        if (_found EQUAL -1 AND ARGC GREATER 3)
            foreach (_index RANGE 3 ${_last})
                string(FIND "${ARGV${_index}}" "${_separator}" _found)
                if (NOT _found EQUAL -1)
                    break()
                endif()
            endforeach()
        endif()
        if (_found EQUAL -1)
            break()
        endif()
        string(APPEND _separator "_")
    endwhile()
    set(_arguments "")
    if (ARGC GREATER 3)
        foreach (_index RANGE 3 ${_last})
            string(REPLACE ";" "${_separator}" _argument "${ARGV${_index}}")
            list(APPEND _arguments "${_argument}")
        endforeach()
    endif()
    set(${_output} "${_arguments}" PARENT_SCOPE)
    set(${_separator_output} "${_separator}" PARENT_SCOPE)
endfunction()

# Autoconf's CC/CXX are shell commands, unlike CMake's launcher argv lists.
function(_reaveros_shell_command _output)
    set(_command "")
    math(EXPR _last "${ARGC} - 1")
    foreach (_index RANGE 1 ${_last})
        string(REPLACE "'" "'\"'\"'" _argument "${ARGV${_index}}")
        if (NOT _command STREQUAL "")
            string(APPEND _command " ")
        endif()
        string(APPEND _command "'${_argument}'")
    endforeach()
    set(${_output} "${_command}" PARENT_SCOPE)
endfunction()
