include_guard(GLOBAL)

function(reaveros_require_host_tools _feature)
    foreach (_tool IN LISTS ARGN)
        string(TOUPPER "${_tool}" _name)
        set(_variable "REAVEROS_HOST_${_name}")
        find_program(${_variable} NAMES "${_tool}")
        mark_as_advanced(${_variable})
        if (NOT ${_variable} OR NOT EXISTS "${${_variable}}" OR IS_DIRECTORY "${${_variable}}")
            message(FATAL_ERROR "${_feature} requires the host tool '${_tool}'. Install it or set ${_variable} to its executable.")
        endif()
        get_property(_checked GLOBAL PROPERTY "_REAVEROS_CHECKED_${_name}")
        if (_checked STREQUAL "${${_variable}}")
            continue()
        endif()
        set(_probe --version)
        if (_tool STREQUAL "awk")
            set(_probe "BEGIN { exit 0 }")
        endif()
        execute_process(COMMAND "${${_variable}}" ${_probe}
            RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
        if (NOT _result STREQUAL "0")
            message(FATAL_ERROR "${_feature} cannot run host tool '${_tool}' at '${${_variable}}': ${_result}\n${_error}")
        endif()
        if ((_tool STREQUAL "find" OR _tool STREQUAL "cpio") AND NOT _output MATCHES "GNU")
            message(FATAL_ERROR "${_feature} requires GNU ${_tool}; selected '${${_variable}}'.")
        endif()
        set_property(GLOBAL PROPERTY "_REAVEROS_CHECKED_${_name}" "${${_variable}}")
    endforeach()
endfunction()

macro(reaveros_require_host_python)
    get_property(_reaveros_python GLOBAL PROPERTY _REAVEROS_HOST_PYTHON)
    if (_reaveros_python)
        set(Python3_EXECUTABLE "${_reaveros_python}")
    else()
        find_package(Python3 3.9 REQUIRED COMPONENTS Interpreter)
        set_property(GLOBAL PROPERTY _REAVEROS_HOST_PYTHON "${Python3_EXECUTABLE}")
    endif()
endmacro()
