cmake_minimum_required(VERSION 3.31)

foreach (_argument IN ITEMS REAVEROS_BUILD_ROOT REAVEROS_INSTALL_PROJECT
        REAVEROS_INSTALL_BINARY_DIR REAVEROS_INSTALL_CMAKE)
    if (NOT DEFINED ${_argument} OR "${${_argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing install argument ${_argument}")
    endif()
endforeach()
if (NOT REAVEROS_INSTALL_PROJECT MATCHES "^[a-zA-Z0-9][a-zA-Z0-9_.-]*$")
    message(FATAL_ERROR "Invalid install project '${REAVEROS_INSTALL_PROJECT}'")
endif()

cmake_path(ABSOLUTE_PATH REAVEROS_BUILD_ROOT NORMALIZE)
set(_install_root "${REAVEROS_BUILD_ROOT}/install")
set(_ownership_dir "${REAVEROS_BUILD_ROOT}/cmake/install-ownership")
set(_project_dir "${REAVEROS_BUILD_ROOT}/cmake/install-projects")
set(_stage "${REAVEROS_BUILD_ROOT}/cmake/install-staging/${REAVEROS_INSTALL_PROJECT}")
set(_manifest "${REAVEROS_INSTALL_BINARY_DIR}/install_manifest.txt")
set(_ownership "${_ownership_dir}/${REAVEROS_INSTALL_PROJECT}.txt")

# Install manifests and publication must be checked together. This also keeps
# two Make invocations from staging the same project concurrently.
file(MAKE_DIRECTORY "${_ownership_dir}")
file(LOCK "${_ownership_dir}/lock" GUARD PROCESS TIMEOUT 300)

if (EXISTS "${_manifest}")
    file(READ "${_manifest}" _original_manifest)
    set(_had_manifest TRUE)
else()
    set(_had_manifest FALSE)
endif()

function(_install_error _message)
    if (_had_manifest)
        file(WRITE "${_manifest}" "${_original_manifest}")
    else()
        file(REMOVE "${_manifest}")
    endif()
    file(REMOVE_RECURSE "${_stage}")
    message(FATAL_ERROR "${_message}")
endfunction()

function(_read_manifest _file _output)
    set(_files "")
    if (EXISTS "${_file}")
        file(STRINGS "${_file}" _entries ENCODING UTF-8)
        foreach (_path IN LISTS _entries)
            if (_path STREQUAL "")
                continue()
            endif()
            cmake_path(IS_ABSOLUTE _path _absolute)
            cmake_path(NORMAL_PATH _path)
            cmake_path(IS_PREFIX _install_root "${_path}" NORMALIZE _inside)
            if (NOT _absolute OR NOT _inside OR _path STREQUAL _install_root)
                _install_error("Install manifest '${_file}' claims a path outside the install tree: ${_path}")
            endif()
            list(APPEND _files "${_path}")
        endforeach()
        list(REMOVE_DUPLICATES _files)
    endif()
    set(${_output} "${_files}" PARENT_SCOPE)
endfunction()

function(_write_manifest _file _files)
    list(SORT _files)
    string(JOIN "\n" _content ${_files})
    if (_files)
        string(APPEND _content "\n")
    endif()
    file(WRITE "${_file}.tmp" "${_content}")
    file(RENAME "${_file}.tmp" "${_file}")
endfunction()

# A parent-authored descriptor names one former owner and bounded install paths.
# Retire those claims only after a successful, validated staged installation.
set(_transfer_files "")
set(_transfer_from "")
if (DEFINED REAVEROS_INSTALL_TRANSFER_FILE AND NOT REAVEROS_INSTALL_TRANSFER_FILE STREQUAL "")
    file(STRINGS "${REAVEROS_INSTALL_TRANSFER_FILE}" _transfer ENCODING UTF-8)
    list(LENGTH _transfer _length)
    if (_length LESS 2)
        _install_error("Install transfer must name a former owner and at least one install root")
    endif()
    list(POP_FRONT _transfer _transfer_from)
    if (NOT _transfer_from MATCHES "^[a-zA-Z0-9][a-zA-Z0-9_.-]*$"
            OR _transfer_from STREQUAL REAVEROS_INSTALL_PROJECT)
        _install_error("Invalid former install owner '${_transfer_from}'")
    endif()
    set(_transfer_roots "")
    foreach (_root IN LISTS _transfer)
        if (IS_ABSOLUTE "${_root}")
            _install_error("Install transfer root must be relative to install: ${_root}")
        endif()
        set(_root "${_install_root}/${_root}")
        cmake_path(NORMAL_PATH _root)
        cmake_path(IS_PREFIX _install_root "${_root}" NORMALIZE _inside)
        if (NOT _inside OR _root STREQUAL _install_root)
            _install_error("Install transfer root is outside a bounded install subtree: ${_root}")
        endif()
        list(APPEND _transfer_roots "${_root}")
    endforeach()

    set(_transfer_ownership "${_ownership_dir}/${_transfer_from}.txt")
    set(_transfer_manifest "")
    if (EXISTS "${_project_dir}/${_transfer_from}.txt")
        file(READ "${_project_dir}/${_transfer_from}.txt" _transfer_manifest)
        string(STRIP "${_transfer_manifest}" _transfer_manifest)
    endif()
    if (EXISTS "${_transfer_ownership}")
        set(_transfer_source "${_transfer_ownership}")
    else()
        set(_transfer_source "${_transfer_manifest}")
    endif()
    _read_manifest("${_transfer_source}" _transfer_previous)
    set(_transfer_remaining "${_transfer_previous}")
    foreach (_path IN LISTS _transfer_previous)
        foreach (_root IN LISTS _transfer_roots)
            cmake_path(IS_PREFIX _root "${_path}" NORMALIZE _matches)
            if (_matches)
                list(APPEND _transfer_files "${_path}")
                list(REMOVE_ITEM _transfer_remaining "${_path}")
                break()
            endif()
        endforeach()
    endforeach()
endif()

if (EXISTS "${_ownership}")
    _read_manifest("${_ownership}" _previous_files)
else()
    _read_manifest("${_manifest}" _previous_files)
endif()
list(APPEND _previous_files ${_transfer_files})

# DESTDIR stages absolute destinations too, including the kernel's hosted
# syscall/vDSO outputs. Nothing reaches the shared sysroots before validation.
file(REMOVE_RECURSE "${_stage}")
file(MAKE_DIRECTORY "${_stage}")
# Publication relocates the stage, so CMake-created relative source links break.
# COPY retains ordinary package-internal symlinks such as versioned libraries.
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "DESTDIR=${_stage}" "CMAKE_INSTALL_MODE=COPY"
        "${REAVEROS_INSTALL_CMAKE}" --install "${REAVEROS_INSTALL_BINARY_DIR}"
    RESULT_VARIABLE _result
)
if (NOT _result STREQUAL "0")
    _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' failed: ${_result}")
endif()
if (NOT EXISTS "${_manifest}")
    _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' produced no install manifest")
endif()
_read_manifest("${_manifest}" _current_files)

file(GLOB _owners "${_ownership_dir}/*.txt" "${_project_dir}/*.txt")
foreach (_path IN LISTS _current_files _transfer_files)
    string(SHA256 _path_hash "${_path}")
    set(_file_owner_${_path_hash} "${REAVEROS_INSTALL_PROJECT}")
endforeach()
set(_seen_owners "${REAVEROS_INSTALL_PROJECT}")
set(_other_files "")
foreach (_owner_file IN LISTS _owners)
    cmake_path(GET _owner_file STEM _owner)
    if (_owner IN_LIST _seen_owners)
        continue()
    endif()
    list(APPEND _seen_owners "${_owner}")
    if (EXISTS "${_ownership_dir}/${_owner}.txt")
        set(_owner_manifest "${_ownership_dir}/${_owner}.txt")
    else()
        file(READ "${_project_dir}/${_owner}.txt" _owner_manifest)
        string(STRIP "${_owner_manifest}" _owner_manifest)
    endif()
    _read_manifest("${_owner_manifest}" _claimed_files)
    if (_owner STREQUAL _transfer_from)
        set(_claimed_files "${_transfer_remaining}")
    endif()
    foreach (_path IN LISTS _claimed_files)
        string(SHA256 _path_hash "${_path}")
        if (DEFINED _file_owner_${_path_hash})
            _install_error("Install ownership conflict: '${_file_owner_${_path_hash}}' and '${_owner}' both claim '${_path}'")
        endif()
        set(_file_owner_${_path_hash} "${_owner}")
    endforeach()
    list(APPEND _other_files ${_claimed_files})
endforeach()

foreach (_path IN LISTS _current_files)
    if (NOT EXISTS "${_stage}${_path}" AND NOT IS_SYMLINK "${_stage}${_path}")
        _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' did not stage '${_path}'")
    endif()
endforeach()

foreach (_path IN LISTS _current_files)
    cmake_path(GET _path PARENT_PATH _destination)
    # A file/symlink transition must replace the previous directory entry.
    if (IS_SYMLINK "${_path}" OR (EXISTS "${_path}" AND IS_SYMLINK "${_stage}${_path}"))
        if (IS_SYMLINK "${_path}" AND IS_SYMLINK "${_stage}${_path}")
            file(READ_SYMLINK "${_path}" _old_target)
            file(READ_SYMLINK "${_stage}${_path}" _new_target)
            if (_old_target STREQUAL _new_target)
                continue()
            endif()
        endif()
        file(REMOVE "${_path}")
    endif()
    if (NOT IS_SYMLINK "${_stage}${_path}")
        # COPY preserves permissions/timestamps but may skip different contents
        # with the same timestamp, including an artifact from a former owner.
        file(MAKE_DIRECTORY "${_destination}")
        file(COPY_FILE "${_stage}${_path}" "${_path}" ONLY_IF_DIFFERENT)
    endif()
    file(COPY "${_stage}${_path}" DESTINATION "${_destination}")
endforeach()

foreach (_path IN LISTS _previous_files)
    if (NOT _path IN_LIST _current_files AND NOT _path IN_LIST _other_files)
        file(REMOVE "${_path}")
        if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
            _install_error("Could not remove obsolete file '${_path}' from '${REAVEROS_INSTALL_PROJECT}'")
        endif()
    endif()
endforeach()

if (_transfer_from AND EXISTS "${_transfer_source}")
    # Trim the legacy child manifest first so later adoption cannot resurrect
    # the old claims. A retry can recover from either trimmed record because
    # the new child's successful install manifest already lists its outputs.
    if (EXISTS "${_transfer_manifest}")
        _read_manifest("${_transfer_manifest}" _legacy_files)
        foreach (_path IN LISTS _legacy_files)
            foreach (_root IN LISTS _transfer_roots)
                cmake_path(IS_PREFIX _root "${_path}" NORMALIZE _matches)
                if (_matches)
                    list(REMOVE_ITEM _legacy_files "${_path}")
                    break()
                endif()
            endforeach()
        endforeach()
        _write_manifest("${_transfer_manifest}" "${_legacy_files}")
    endif()
    _write_manifest("${_transfer_ownership}" "${_transfer_remaining}")
    if (_transfer_files)
        message(STATUS "Transferred interface installation from '${_transfer_from}' to '${REAVEROS_INSTALL_PROJECT}'")
    endif()
endif()
_write_manifest("${_ownership}" "${_current_files}")
file(REMOVE_RECURSE "${_stage}")
