cmake_minimum_required(VERSION 3.31)

foreach (_argument IN ITEMS REAVEROS_BUILD_ROOT REAVEROS_INSTALL_PROJECT
        REAVEROS_INSTALL_BINARY_DIR REAVEROS_INSTALL_CMAKE)
    if (NOT DEFINED ${_argument} OR "${${_argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing install argument ${_argument}")
    endif()
endforeach()
if (NOT REAVEROS_INSTALL_PROJECT MATCHES "^[a-zA-Z0-9][a-zA-Z0-9_.-]*$")
    message(FATAL_ERROR "Invalid install project '${REAVEROS_INSTALL_PROJECT}'")
endif()

cmake_path(ABSOLUTE_PATH REAVEROS_BUILD_ROOT NORMALIZE)
set(_install_root "${REAVEROS_BUILD_ROOT}/install")
set(_ownership_dir "${REAVEROS_BUILD_ROOT}/cmake/install-ownership")
set(_project_dir "${REAVEROS_BUILD_ROOT}/cmake/install-projects")
set(_stage "${REAVEROS_BUILD_ROOT}/cmake/install-staging/${REAVEROS_INSTALL_PROJECT}")
set(_manifest "${REAVEROS_INSTALL_BINARY_DIR}/install_manifest.txt")
set(_ownership "${_ownership_dir}/${REAVEROS_INSTALL_PROJECT}.txt")

# Install manifests and publication must be checked together. This also keeps
# two Make invocations from staging the same project concurrently.
file(MAKE_DIRECTORY "${_ownership_dir}")
file(LOCK "${_ownership_dir}/lock" GUARD PROCESS TIMEOUT 300)

if (EXISTS "${_manifest}")
    file(READ "${_manifest}" _original_manifest)
    set(_had_manifest TRUE)
else()
    set(_had_manifest FALSE)
endif()

function(_install_error _message)
    if (_had_manifest)
        file(WRITE "${_manifest}" "${_original_manifest}")
    else()
        file(REMOVE "${_manifest}")
    endif()
    file(REMOVE_RECURSE "${_stage}")
    message(FATAL_ERROR "${_message}")
endfunction()

function(_read_manifest _file _output)
    set(_files "")
    if (EXISTS "${_file}")
        file(STRINGS "${_file}" _entries ENCODING UTF-8)
        foreach (_path IN LISTS _entries)
            if (_path STREQUAL "")
                continue()
            endif()
            cmake_path(IS_ABSOLUTE _path _absolute)
            cmake_path(NORMAL_PATH _path)
            cmake_path(IS_PREFIX _install_root "${_path}" NORMALIZE _inside)
            if (NOT _absolute OR NOT _inside OR _path STREQUAL _install_root)
                _install_error("Install manifest '${_file}' claims a path outside the install tree: ${_path}")
            endif()
            list(APPEND _files "${_path}")
        endforeach()
        list(REMOVE_DUPLICATES _files)
    endif()
    set(${_output} "${_files}" PARENT_SCOPE)
endfunction()

if (EXISTS "${_ownership}")
    _read_manifest("${_ownership}" _previous_files)
else()
    _read_manifest("${_manifest}" _previous_files)
endif()

# DESTDIR stages absolute destinations too, including the kernel's hosted
# syscall/vDSO outputs. Nothing reaches the shared sysroots before validation.
file(REMOVE_RECURSE "${_stage}")
file(MAKE_DIRECTORY "${_stage}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "DESTDIR=${_stage}"
        "${REAVEROS_INSTALL_CMAKE}" --install "${REAVEROS_INSTALL_BINARY_DIR}"
    RESULT_VARIABLE _result
)
if (NOT _result STREQUAL "0")
    _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' failed: ${_result}")
endif()
if (NOT EXISTS "${_manifest}")
    _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' produced no install manifest")
endif()
_read_manifest("${_manifest}" _current_files)

file(GLOB _owners "${_ownership_dir}/*.txt" "${_project_dir}/*.txt")
foreach (_path IN LISTS _current_files)
    string(SHA256 _path_hash "${_path}")
    set(_file_owner_${_path_hash} "${REAVEROS_INSTALL_PROJECT}")
endforeach()
set(_seen_owners "${REAVEROS_INSTALL_PROJECT}")
set(_other_files "")
foreach (_owner_file IN LISTS _owners)
    cmake_path(GET _owner_file STEM _owner)
    if (_owner IN_LIST _seen_owners)
        continue()
    endif()
    list(APPEND _seen_owners "${_owner}")
    if (EXISTS "${_ownership_dir}/${_owner}.txt")
        set(_owner_manifest "${_ownership_dir}/${_owner}.txt")
    else()
        file(READ "${_project_dir}/${_owner}.txt" _owner_manifest)
        string(STRIP "${_owner_manifest}" _owner_manifest)
    endif()
    _read_manifest("${_owner_manifest}" _claimed_files)
    foreach (_path IN LISTS _claimed_files)
        string(SHA256 _path_hash "${_path}")
        if (DEFINED _file_owner_${_path_hash})
            _install_error("Install ownership conflict: '${_file_owner_${_path_hash}}' and '${_owner}' both claim '${_path}'")
        endif()
        set(_file_owner_${_path_hash} "${_owner}")
    endforeach()
    list(APPEND _other_files ${_claimed_files})
endforeach()

foreach (_path IN LISTS _current_files)
    if (NOT EXISTS "${_stage}${_path}" AND NOT IS_SYMLINK "${_stage}${_path}")
        _install_error("Installation of '${REAVEROS_INSTALL_PROJECT}' did not stage '${_path}'")
    endif()
endforeach()

foreach (_path IN LISTS _current_files)
    cmake_path(GET _path PARENT_PATH _destination)
    # A file/symlink transition must replace the previous directory entry.
    if (IS_SYMLINK "${_path}" OR (EXISTS "${_path}" AND IS_SYMLINK "${_stage}${_path}"))
        if (IS_SYMLINK "${_path}" AND IS_SYMLINK "${_stage}${_path}")
            file(READ_SYMLINK "${_path}" _old_target)
            file(READ_SYMLINK "${_stage}${_path}" _new_target)
            if (_old_target STREQUAL _new_target)
                continue()
            endif()
        endif()
        file(REMOVE "${_path}")
    endif()
    file(COPY "${_stage}${_path}" DESTINATION "${_destination}")
endforeach()

foreach (_path IN LISTS _previous_files)
    if (NOT _path IN_LIST _current_files AND NOT _path IN_LIST _other_files)
        file(REMOVE "${_path}")
        if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
            _install_error("Could not remove obsolete file '${_path}' from '${REAVEROS_INSTALL_PROJECT}'")
        endif()
    endif()
endforeach()

list(SORT _current_files)
string(JOIN "\n" _content ${_current_files})
if (_current_files)
    string(APPEND _content "\n")
endif()
file(WRITE "${_ownership}.tmp" "${_content}")
file(RENAME "${_ownership}.tmp" "${_ownership}")
file(REMOVE_RECURSE "${_stage}")
