include_guard(GLOBAL)

# Component-local definitions/options are inherited from the calling directory.
# Only the shared executable naming, assertion policy, and build target live here.
function(reaveros_add_native_tests)
    cmake_parse_arguments(PARSE_ARGV 0 _tests "" "" "LIBRARIES")
    if (_tests_UNPARSED_ARGUMENTS OR _tests_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid native-test arguments: ${_tests_UNPARSED_ARGUMENTS} ${_tests_KEYWORDS_MISSING_VALUES}")
    endif()
    add_custom_target(build-tests)
    file(GLOB_RECURSE _files RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" CONFIGURE_DEPENDS *.test.cpp)
    foreach (_file IN LISTS _files)
        string(REPLACE "/" "--" _executable "${_file}")
        string(REGEX REPLACE "\\.test\\.cpp$" ".test" _executable "${_executable}")
        string(REGEX REPLACE "\\.test\\.cpp$" "" _name "${_file}")
        add_executable("${_executable}" "${_file}")
        target_compile_options("${_executable}" PRIVATE -UNDEBUG)
        if (_tests_LIBRARIES)
            target_link_libraries("${_executable}" PRIVATE ${_tests_LIBRARIES})
        endif()
        add_dependencies(build-tests "${_executable}")
        add_test(NAME "${_name}" COMMAND "${_executable}")
    endforeach()
endfunction()
