include_guard(GLOBAL)

function(_reaveros_json_string _output _value)
    string(REPLACE "\\" "\\\\" _value "${_value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    string(REPLACE "\n" "\\n" _value "${_value}")
    string(REPLACE "\r" "\\r" _value "${_value}")
    string(REPLACE "\t" "\\t" _value "${_value}")
    set(${_output} "\"${_value}\"" PARENT_SCOPE)
endfunction()

function(_reaveros_finalize_toolchain_lifecycles)
    reaveros_require_host_python()
    get_property(_projects DIRECTORY PROPERTY _REAVEROS_LIFECYCLE_PROJECTS)
    foreach (_project IN LISTS _projects)
        ExternalProject_Get_Property(${_project} SOURCE_DIR BINARY_DIR INSTALL_DIR STAMP_DIR TMP_DIR UPDATE_DISCONNECTED)
        set(_contract "{\"version\":1,\"directories\":{},\"identity\":{},\"stamps\":{},\"legacy_inputs\":{},\"required_outputs\":[],\"prune_order\":[]}")
        _reaveros_json_string(_value "${REAVEROS_BINARY_DIR}")
        string(JSON _contract SET "${_contract}" root "${_value}")
        _reaveros_json_string(_value "${_project}")
        string(JSON _contract SET "${_contract}" project "${_value}")
        foreach (_directory SOURCE BINARY INSTALL STAMP)
            string(TOLOWER "${_directory}" _key)
            _reaveros_json_string(_value "${${_directory}_DIR}")
            string(JSON _contract SET "${_contract}" directories ${_key} "${_value}")
        endforeach()
        get_property(_source_id TARGET ${_project} PROPERTY _REAVEROS_SOURCE_ID)
        if (_source_id STREQUAL "")
            message(FATAL_ERROR "Toolchain lifecycle '${_project}' requires source identity.")
        endif()
        _reaveros_json_string(_value "${_source_id}")
        string(JSON _contract SET "${_contract}" identity source "${_value}")
        set(_patch_file "${REAVEROS_BINARY_DIR}/toolchain/${_project}-patch-inputs")
        set(_patch_id "")
        if (EXISTS "${_patch_file}")
            file(READ "${_patch_file}" _patch_id)
            string(JSON _contract SET "${_contract}" legacy_inputs "${_patch_file}" "\"apply-patches\"")
        endif()
        _reaveros_json_string(_value "${_patch_id}")
        string(JSON _contract SET "${_contract}" identity patch "${_value}")

        # Configuration identity tracks output-affecting inputs. Launchers and
        # parallelism affect scheduling and must not discard a valid toolchain.
        _reaveros_ep_configuration_identity(_configuration "${_project}")
        _reaveros_json_string(_value "${_configuration}")
        string(JSON _contract SET "${_contract}" identity configuration "${_value}")
        # Compiler selections also determine whether a configured CMake build
        # tree can be reused safely when other configuration inputs change.
        string(JSON _contract SET "${_contract}" compilers "{}")
        string(JSON _contract SET "${_contract}" identity compilers "{}")
        foreach (_language C CXX)
            set(_compiler "{}")
            foreach (_field COMPILER COMPILER_ARG1)
                _reaveros_json_string(_value "${CMAKE_${_language}_${_field}}")
                string(JSON _compiler SET "${_compiler}" ${_field} "${_value}")
            endforeach()
            string(JSON _contract SET "${_contract}" compilers ${_language} "${_compiler}")
            set(_compiler_hash "")
            if (EXISTS "${CMAKE_${_language}_COMPILER}")
                file(SHA256 "${CMAKE_${_language}_COMPILER}" _compiler_hash)
            endif()
            _reaveros_json_string(_value "${_compiler_hash}")
            string(JSON _contract SET "${_contract}" identity compilers ${_language} "${_value}")
        endforeach()
        string(JSON _contract SET "${_contract}" legacy_inputs
            "${REAVEROS_BINARY_DIR}/toolchain/${_project}-source-inputs" "\"invalidate-build\"")
        foreach (_input tag invalidation)
            set(_file "${REAVEROS_BINARY_DIR}/toolchain/${_project}-${_input}-inputs")
            set(_step invalidate-build)
            if (_input STREQUAL "tag")
                set(_step set-to-tag)
            endif()
            if (EXISTS "${_file}")
                string(JSON _contract SET "${_contract}" legacy_inputs "${_file}" "\"${_step}\"")
            endif()
        endforeach()
        _reaveros_ep_configure_input(_cfgcmd "${_project}")
        string(JSON _contract SET "${_contract}" legacy_inputs "${_cfgcmd}" "\"configure\"")
        foreach (_step mkdir download update update_disconnected patch patch_disconnected
                skip-update set-to-tag hydrate-source apply-patches invalidate-build configure build install done prune complete)
            _reaveros_ep_step_stamp(_path "${_project}" "${_step}")
            _reaveros_json_string(_value "${_path}")
            string(JSON _contract SET "${_contract}" stamps ${_step} "${_value}")
        endforeach()
        get_property(_outputs TARGET ${_project} PROPERTY _REAVEROS_REQUIRED_OUTPUTS)
        set(_index 0)
        foreach (_output IN LISTS _outputs)
            _reaveros_json_string(_value "${_output}")
            string(JSON _contract SET "${_contract}" required_outputs ${_index} "${_value}")
            math(EXPR _index "${_index} + 1")
        endforeach()
        get_property(_source_step TARGET ${_project} PROPERTY _REAVEROS_PRUNE_SOURCE_STEP)
        get_property(_after_patch TARGET ${_project} PROPERTY _REAVEROS_PRUNE_AFTER_PATCH)
        _reaveros_ep_prune_steps(_order "${_source_step}" "${_after_patch}" "${UPDATE_DISCONNECTED}")
        set(_index 0)
        foreach (_step IN LISTS _order)
            _reaveros_json_string(_value "${_step}")
            string(JSON _contract SET "${_contract}" prune_order ${_index} "${_value}")
            math(EXPR _index "${_index} + 1")
        endforeach()
        get_property(_remove_archive TARGET ${_project} PROPERTY _REAVEROS_PRUNE_ARCHIVE)
        if (_remove_archive)
            ExternalProject_Get_Property(${_project} DOWNLOADED_FILE)
            _reaveros_json_string(_value "${DOWNLOADED_FILE}")
            string(JSON _contract SET "${_contract}" archive "${_value}")
        endif()
        set(_file "${REAVEROS_BINARY_DIR}/toolchain/${_project}-lifecycle.json")
        file(GENERATE OUTPUT "${_file}" CONTENT "${_contract}\n")
        set(_helpers "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../toolchain")
        add_custom_target(${_project}-guard
            COMMAND "${Python3_EXECUTABLE}" "${_helpers}/guard-lifecycle" "${REAVEROS_BINARY_DIR}" "${_project}" build "${CMAKE_MAKE_PROGRAM}"
            COMMAND "${Python3_EXECUTABLE}" "${_helpers}/installed-state" check "${_file}"
            VERBATIM)
        add_custom_target(${_project}-prune-guard
            COMMAND "${Python3_EXECUTABLE}" "${_helpers}/guard-lifecycle" "${REAVEROS_BINARY_DIR}" "${_project}" prune "${CMAKE_MAKE_PROGRAM}"
            VERBATIM)
        add_dependencies(${_project} ${_project}-guard)
        foreach (_step mkdir download update update_disconnected patch patch_disconnected
                set-to-tag hydrate-source apply-patches invalidate-build configure build install)
            if (TARGET ${_project}-${_step})
                add_dependencies(${_project}-${_step} ${_project}-guard)
            endif()
        endforeach()
        add_dependencies(${_project}-prune ${_project}-prune-guard)
        add_custom_command(TARGET ${_project}-install POST_BUILD
            COMMAND "${Python3_EXECUTABLE}" "${_helpers}/installed-state" record "${_file}"
            VERBATIM)
    endforeach()
endfunction()
